export const
  DT = 0.01,
  CURL = 1,
  DENSITY_RADIUS = 333,
  FORCE_RADIUS = 1000,
  VELOCITY_SPREAD = 1.8,
  COLOR_INTENSITY = 2,
  PRESSURE_ITERATIONS = 3,
  DENSITY_DISSIPATION = .998,
  VELOCITY_DISSIPATION = 1,
  NUM_PARTICLES = 70000;
